// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owexoreiktzlcntpskrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93ZXhvcmVpa3R6bGNudHBza3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0OTA4MzAsImV4cCI6MjA2MDA2NjgzMH0.dBBHVe2AKy21Y9MGNOwh9yucF-luEMMiiqAw4eUWSyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);